package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type module struct {
	Path    string
	Version string
	Dir     string
	Main    bool
}

type listedPackage struct {
	Module *module
}

type target struct {
	goos, goarch, cgo, tags string
}

var releaseTargets = []target{
	{goos: "windows", goarch: "amd64", cgo: "0"},
	{goos: "darwin", goarch: "amd64", cgo: "1"},
	{goos: "darwin", goarch: "arm64", cgo: "1"},
	{goos: "linux", goarch: "amd64", cgo: "1"},
}

func main() {
	root := repositoryRoot()
	modules := releaseModules(root)
	var output bytes.Buffer
	fmt.Fprintln(&output, "Faro Third-Party Notices")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "This distribution incorporates the third-party software listed below.")
	fmt.Fprintln(&output, "Each component remains subject to its own license terms.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "Generated by: go generate ./internal/legal")

	paths := make([]string, 0, len(modules))
	for path := range modules {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		mod := modules[path]
		files := licenseFiles(mod.Dir)
		if len(files) == 0 {
			fatalf("no license or notice file found for %s", mod.Path)
		}
		fmt.Fprintln(&output)
		fmt.Fprintln(&output, strings.Repeat("=", 78))
		fmt.Fprintf(&output, "%s %s\n", mod.Path, mod.Version)
		for _, name := range files {
			contents, err := os.ReadFile(filepath.Join(mod.Dir, name))
			if err != nil {
				fatalf("read %s %s: %v", mod.Path, name, err)
			}
			fmt.Fprintf(&output, "\n--- %s ---\n\n", name)
			output.Write(bytes.TrimSpace(contents))
			output.WriteByte('\n')
		}
	}

	notices := output.Bytes()
	write(filepath.Join(root, "THIRD_PARTY_NOTICES.txt"), notices)
	write(filepath.Join(root, "internal", "legal", "assets", "THIRD_PARTY_NOTICES.txt"), notices)
	license, err := os.ReadFile(filepath.Join(root, "LICENSE"))
	if err != nil {
		fatalf("read project LICENSE: %v", err)
	}
	write(filepath.Join(root, "internal", "legal", "assets", "MPL-2.0.txt"), license)
}

func repositoryRoot() string {
	command := exec.Command("go", "env", "GOMOD")
	raw, err := command.Output()
	if err != nil {
		fatalf("locate go.mod: %v", err)
	}
	return filepath.Dir(strings.TrimSpace(string(raw)))
}

func releaseModules(root string) map[string]module {
	modules := make(map[string]module)
	for _, current := range releaseTargets {
		args := []string{"list", "-deps", "-json"}
		if current.tags != "" {
			args = append(args, "-tags", current.tags)
		}
		args = append(args, "./...")
		command := exec.Command("go", args...)
		command.Dir = root
		command.Env = targetEnvironment(current)
		stdout, err := command.StdoutPipe()
		if err != nil {
			fatalf("list packages for %s/%s: %v", current.goos, current.goarch, err)
		}
		var stderr bytes.Buffer
		command.Stderr = &stderr
		if err := command.Start(); err != nil {
			fatalf("list packages for %s/%s: %v", current.goos, current.goarch, err)
		}
		decoder := json.NewDecoder(bufio.NewReader(stdout))
		for {
			var pkg listedPackage
			err := decoder.Decode(&pkg)
			if errors.Is(err, io.EOF) {
				break
			}
			if err != nil {
				fatalf("decode package list for %s/%s: %v", current.goos, current.goarch, err)
			}
			if pkg.Module != nil && !pkg.Module.Main && pkg.Module.Path != "" {
				modules[pkg.Module.Path] = *pkg.Module
			}
		}
		if err := command.Wait(); err != nil {
			fatalf("list packages for %s/%s: %v: %s", current.goos, current.goarch, err, strings.TrimSpace(stderr.String()))
		}
	}
	return modules
}

func targetEnvironment(current target) []string {
	result := make([]string, 0, len(os.Environ())+4)
	for _, value := range os.Environ() {
		name, _, _ := strings.Cut(value, "=")
		switch name {
		case "GOOS", "GOARCH", "CGO_ENABLED":
			continue
		}
		result = append(result, value)
	}
	return append(result, "GOOS="+current.goos, "GOARCH="+current.goarch, "CGO_ENABLED="+current.cgo)
}

func licenseFiles(directory string) []string {
	entries, err := os.ReadDir(directory)
	if err != nil {
		fatalf("read module directory %s: %v", directory, err)
	}
	var result []string
	for _, entry := range entries {
		if entry.Type().IsRegular() && isLegalFilename(entry.Name()) {
			result = append(result, entry.Name())
		}
	}
	sort.Strings(result)
	return result
}

func isLegalFilename(name string) bool {
	lower := strings.ToLower(name)
	ext := filepath.Ext(lower)
	if ext != "" && ext != ".txt" && ext != ".md" && ext != ".rst" {
		return false
	}
	base := strings.TrimSuffix(lower, ext)
	return strings.HasPrefix(base, "license") || strings.HasPrefix(base, "copying") ||
		base == "notice" || base == "copyright" || base == "patents"
}

func write(path string, contents []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fatalf("create directory for %s: %v", path, err)
	}
	if previous, err := os.ReadFile(path); err == nil && bytes.Equal(previous, contents) {
		return
	}
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
}

func fatalf(format string, values ...any) {
	fmt.Fprintf(os.Stderr, "generate legal notices: "+format+"\n", values...)
	os.Exit(1)
}
